{% set name = "sphinx-parser" %}
{% set version = "0.0.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b99ef1d2c07401936e196e25d03104a3292acc378ea2938b4463fef623b72bdf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer
  run:
    - python >={{ python_min }}
    - numpy >=1.26.4, <=2.2.0
    - ase =3.23.0

test:
  imports:
    - sphinx_parser
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pyiron/sphinx_parser
  summary: 'Parser for the DFT program SPHInX'
  description: |
    sphinx_parser is the python input and output parser of the DFT code SPHInX
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  # The doc_url and dev_url are optional.
  doc_url: https://sphinx_parser.readthedocs.io/
  dev_url: https://github.com/pyiron/sphinx_parser

extra:
  recipe-maintainers:
    - samwaseda
